// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.14.0
// source: internal/message/pb/object.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutInitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lun           string                 `protobuf:"bytes,1,opt,name=lun,proto3" json:"lun,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	MetaKey       string                 `protobuf:"bytes,3,opt,name=metaKey,proto3" json:"metaKey,omitempty"`
	NoGet         bool                   `protobuf:"varint,4,opt,name=no_get,json=noGet,proto3" json:"no_get,omitempty"`
	Replace       bool                   `protobuf:"varint,5,opt,name=replace,proto3" json:"replace,omitempty"`
	Recover       bool                   `protobuf:"varint,6,opt,name=recover,proto3" json:"recover,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutInitRequest) Reset() {
	*x = PutInitRequest{}
	mi := &file_internal_message_pb_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutInitRequest) ProtoMessage() {}

func (x *PutInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_pb_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutInitRequest.ProtoReflect.Descriptor instead.
func (*PutInitRequest) Descriptor() ([]byte, []int) {
	return file_internal_message_pb_object_proto_rawDescGZIP(), []int{0}
}

func (x *PutInitRequest) GetLun() string {
	if x != nil {
		return x.Lun
	}
	return ""
}

func (x *PutInitRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PutInitRequest) GetMetaKey() string {
	if x != nil {
		return x.MetaKey
	}
	return ""
}

func (x *PutInitRequest) GetNoGet() bool {
	if x != nil {
		return x.NoGet
	}
	return false
}

func (x *PutInitRequest) GetReplace() bool {
	if x != nil {
		return x.Replace
	}
	return false
}

func (x *PutInitRequest) GetRecover() bool {
	if x != nil {
		return x.Recover
	}
	return false
}

type FileMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lun           string                 `protobuf:"bytes,1,opt,name=lun,proto3" json:"lun,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Etag          string                 `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Offset        []int64                `protobuf:"varint,5,rep,packed,name=offset,proto3" json:"offset,omitempty"`
	Len           []int64                `protobuf:"varint,6,rep,packed,name=len,proto3" json:"len,omitempty"`
	MetaKey       string                 `protobuf:"bytes,7,opt,name=metaKey,proto3" json:"metaKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMeta) Reset() {
	*x = FileMeta{}
	mi := &file_internal_message_pb_object_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMeta) ProtoMessage() {}

func (x *FileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_pb_object_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMeta.ProtoReflect.Descriptor instead.
func (*FileMeta) Descriptor() ([]byte, []int) {
	return file_internal_message_pb_object_proto_rawDescGZIP(), []int{1}
}

func (x *FileMeta) GetLun() string {
	if x != nil {
		return x.Lun
	}
	return ""
}

func (x *FileMeta) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileMeta) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *FileMeta) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMeta) GetOffset() []int64 {
	if x != nil {
		return x.Offset
	}
	return nil
}

func (x *FileMeta) GetLen() []int64 {
	if x != nil {
		return x.Len
	}
	return nil
}

func (x *FileMeta) GetMetaKey() string {
	if x != nil {
		return x.MetaKey
	}
	return ""
}

var File_internal_message_pb_object_proto protoreflect.FileDescriptor

const file_internal_message_pb_object_proto_rawDesc = "" +
	"\n" +
	" internal/message/pb/object.proto\x12\bcorgi.pb\"\xa3\x01\n" +
	"\x0ePutInitRequest\x12\x10\n" +
	"\x03lun\x18\x01 \x01(\tR\x03lun\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\x12\x18\n" +
	"\ametaKey\x18\x03 \x01(\tR\ametaKey\x12\x15\n" +
	"\x06no_get\x18\x04 \x01(\bR\x05noGet\x12\x18\n" +
	"\areplace\x18\x05 \x01(\bR\areplace\x12\x18\n" +
	"\arecover\x18\x06 \x01(\bR\arecover\"\xa4\x01\n" +
	"\bFileMeta\x12\x10\n" +
	"\x03lun\x18\x01 \x01(\tR\x03lun\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\x12\x12\n" +
	"\x04etag\x18\x03 \x01(\tR\x04etag\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x16\n" +
	"\x06offset\x18\x05 \x03(\x03R\x06offset\x12\x10\n" +
	"\x03len\x18\x06 \x03(\x03R\x03len\x12\x18\n" +
	"\ametaKey\x18\a \x01(\tR\ametaKeyB\x1eZ\x1cCorgi/internal/message/pb;pbb\x06proto3"

var (
	file_internal_message_pb_object_proto_rawDescOnce sync.Once
	file_internal_message_pb_object_proto_rawDescData []byte
)

func file_internal_message_pb_object_proto_rawDescGZIP() []byte {
	file_internal_message_pb_object_proto_rawDescOnce.Do(func() {
		file_internal_message_pb_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_message_pb_object_proto_rawDesc), len(file_internal_message_pb_object_proto_rawDesc)))
	})
	return file_internal_message_pb_object_proto_rawDescData
}

var file_internal_message_pb_object_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_message_pb_object_proto_goTypes = []any{
	(*PutInitRequest)(nil), // 0: corgi.pb.PutInitRequest
	(*FileMeta)(nil),       // 1: corgi.pb.FileMeta
}
var file_internal_message_pb_object_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_message_pb_object_proto_init() }
func file_internal_message_pb_object_proto_init() {
	if File_internal_message_pb_object_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_message_pb_object_proto_rawDesc), len(file_internal_message_pb_object_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_message_pb_object_proto_goTypes,
		DependencyIndexes: file_internal_message_pb_object_proto_depIdxs,
		MessageInfos:      file_internal_message_pb_object_proto_msgTypes,
	}.Build()
	File_internal_message_pb_object_proto = out.File
	file_internal_message_pb_object_proto_goTypes = nil
	file_internal_message_pb_object_proto_depIdxs = nil
}
